In [1]:
import numpy as np
x = np.arange(10, 20)
print(x)

y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(y)


[10 11 12 13 14 15 16 17 18 19]
[ 2  1  4  5  8 12 18 25 96 48]


NumPy Correlation Calculation

In [2]:
r = np.corrcoef(x, y)

In [3]:
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [4]:
r[0, 1]

0.7586402890911867

In [5]:
r[1, 0]

0.7586402890911869

The values on the main diagonal of the correlation matrix (upper left and lower right) are equal to 1.

The upper left value corresponds to the correlation coefficient for x and x, while the lower right value is the correlation coefficient for y and y.

They are always equal to 1.

pearsonr()

spearmanr()

kendalltau()

SciPy Correlation Calculation

In [7]:
import numpy as np
import scipy.stats

x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

print(scipy.stats.pearsonr(x, y))    # Pearson's r

print(scipy.stats.spearmanr(x, y))   # Spearman's rho

print(scipy.stats.kendalltau(x, y))  # Kendall's tau


(0.7586402890911869, 0.010964341301680832)
SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)
KendalltauResult(correlation=0.911111111111111, pvalue=2.9761904761904762e-05)


In [8]:
print(scipy.stats.pearsonr(x, y)[0])    # Pearson's r

print(scipy.stats.spearmanr(x, y)[0])   # Spearman's rho

print(scipy.stats.kendalltau(x, y)[0])  # Kendall's tau

0.7586402890911869
0.9757575757575757
0.911111111111111


In [ ]:
scipy.stats.spearmanr(x, y).correlation   # Spearman's rho

In [ ]:
scipy.stats.kendalltau(x, y).correlation  # Kendall's tau

Pandas Correlation Calculation

In [9]:
import pandas as pd
x = pd.Series(range(10, 20))
print(x)

y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(y)


x.corr(y)                     # Pearson's r

y.corr(x)

print(x.corr(y, method='spearman'))  # Spearman's rho

print(x.corr(y, method='kendall'))   # Kendall's tau


0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64
0.9757575757575757
0.911111111111111


Example

In [ ]:
import pandas as pd
x = pd.Series([14.2,16.4,11.9,15.2,18.5,22.1,19.4,25.1,23.4,18.1,22.6,17.2])
print(x)

y = pd.Series([215,325,185,332,406,522,412,614,544,421,445,408])
print(y)


x.corr(y)                     # Pearson's r

y.corr(x)

print(x.corr(y, method='spearman'))  # Spearman's rho

print(x.corr(y, method='kendall'))   # Kendall's tau
