"""
Simple Linear/Multiple Linear/ Polynomial Regression

The dependent features are called the dependent variables, outputs, or
      responses.
     
The independent features are called the independent variables, inputs, or
       predictors.
"""

In [1]:
# Simple Linear Regression
import numpy as np
from sklearn.linear_model import LinearRegression

In [30]:
x = np.array([95, 85, 80, 70, 60]).reshape((-1, 1))
y = np.array([85,95,70,65,70])

In [31]:
""" 
call .reshape() on x because this array is required to be two-dimensional, or 
to be more precise, to have one column and as many rows as necessary.
"""

' \ncall .reshape() on x because this array is required to be two-dimensional, or \nto be more precise, to have one column and as many rows as necessary.\n'

In [32]:
print(x)

[[95]
 [85]
 [80]
 [70]
 [60]]


In [33]:
print(y)

[85 95 70 65 70]


In [34]:
model = LinearRegression().fit(x, y)

In [35]:
r_sq = model.score(x, y)

In [36]:
"""
obtain the coefficient of determination (𝑅²) with .score() called on model
"""

'\nobtain the coefficient of determination (𝑅²) with .score() called on model\n'

In [37]:
print('intercept:', model.intercept_)

intercept: 26.780821917808225


In [38]:
#print('coefficient of determination:', r_sq)

In [39]:
print('slope:', model.coef_)

slope: [0.64383562]


In [40]:
# provide y as a two-dimensional array as well

In [41]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [42]:
print('intercept:', new_model.intercept_)

intercept: [26.78082192]


In [43]:
print('slope:', new_model.coef_)

slope: [[0.64383562]]


In [44]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[87.94520548 81.50684932 78.28767123 71.84931507 65.4109589 ]


In [45]:
y_pred.reshape(5,1)

array([[87.94520548],
       [81.50684932],
       [78.28767123],
       [71.84931507],
       [65.4109589 ]])

In [46]:
import sklearn.metrics as metrics

mae = metrics.mean_absolute_error(y, y_pred)

mse = metrics.mean_squared_error(y, y_pred)

rmse = np.sqrt(mse) # or mse**(0.5)  

r2 = metrics.r2_score(y,y_pred)

print("Results of sklearn.metrics:")
print("MAE:",mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R-Squared:", r2)

Results of sklearn.metrics:
MAE: 7.232876712328766
MSE: 65.4794520547945
RMSE: 8.09193747224943
R-Squared: 0.4803218090889325


In [19]:
# Mean Absolute Error

In [20]:
y_pred.reshape(5,1)

array([[87.94520548],
       [81.50684932],
       [78.28767123],
       [71.84931507],
       [65.4109589 ]])

In [21]:
# predict unkown data

In [22]:
y_pred = model.intercept_ + model.coef_ * 80

In [23]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[78.28767123]


In [24]:
# Multiple Linear Regression 

In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [26]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [ ]:
print(y)

In [ ]:
model = LinearRegression().fit(x, y)

In [ ]:
r_sq = model.score(x, y)

In [ ]:
print('coefficient of determination:', r_sq)

In [ ]:
print('intercept:', model.intercept_)

In [ ]:
print('slope:', model.coef_)

In [ ]:
""" 
.intercept_ holds the bias 𝑏₀, while now .coef_ is an array containing 𝑏₁ and 𝑏₂ respectively.
"""

In [ ]:
y_pred = model.predict(x)

In [ ]:
print('predicted response:', y_pred, sep='\n')