In [ ]:
"""
Simple Linear/Multiple Linear/ Polynomial Regression

The dependent features are called the dependent variables, outputs, or
      responses.
     
The independent features are called the independent variables, inputs, or
       predictors.
"""

In [2]:
# Simple Linear Regression
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([95, 85, 80, 70, 60]).reshape((-1, 1))
y = np.array([85,95,70,65,70])

In [4]:
""" 
call .reshape() on x because this array is required to be two-dimensional, or 
to be more precise, to have one column and as many rows as necessary.
"""

' \ncall .reshape() on x because this array is required to be two-dimensional, or \nto be more precise, to have one column and as many rows as necessary.\n'

In [5]:
print(x)

[[95]
 [85]
 [80]
 [70]
 [60]]


In [6]:
print(y)

[85 95 70 65 70]


In [ ]:
model = LinearRegression()

parameters to LinearRegression:

fit_intercept is a Boolean (True by default) that decides whether to calculate 
           the intercept 𝑏₀ (True) or consider it equal to zero (False).

normalize is a Boolean (False by default) that decides whether to normalize 
           the input variables (True) or not (False).

copy_X is a Boolean (True by default) that decides whether to copy (True) or 
           overwrite the input variables (False).

n_jobs is an integer or None (default) and represents the number of jobs used in
       parallel computation. None usually means one job and -1 to use all processo

In [8]:
model = LinearRegression().fit(x, y)

In [9]:
r_sq = model.score(x, y)

In [10]:
"""
obtain the coefficient of determination (𝑅²) with .score() called on model
"""

'\nobtain the coefficient of determination (𝑅²) with .score() called on model\n'

In [11]:
print('intercept:', model.intercept_)

intercept: 26.780821917808225


In [12]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.4803218090889325


In [14]:
print('slope:', model.coef_)

slope: [0.64383562]


In [15]:
# provide y as a two-dimensional array as well

In [16]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [17]:
print('intercept:', new_model.intercept_)

intercept: [26.78082192]


In [18]:
print('slope:', new_model.coef_)

slope: [[0.64383562]]


In [19]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[87.94520548 81.50684932 78.28767123 71.84931507 65.4109589 ]


In [20]:
y_pred = model.intercept_ + model.coef_ * 80
y_pred

array([78.28767123])

In [21]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[78.28767123]


In [22]:
# Multiple Linear Regression 

In [23]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], 
     [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [ ]:
print(x)

In [ ]:
print(y)

In [ ]:
model = LinearRegression().fit(x, y)

In [ ]:
r_sq = model.score(x, y)

In [ ]:
print('coefficient of determination:', r_sq)

In [ ]:
print('intercept:', model.intercept_)

In [ ]:
print('slope:', model.coef_)

In [ ]:
""" 
.intercept_ holds the bias 𝑏₀, while now .coef_ is an array containing 𝑏₁ and 𝑏₂ respectively.
"""

In [ ]:
y_pred = model.predict(x)

In [ ]:
print('predicted response:', y_pred, sep='\n')

In [ ]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)

In [ ]:
print('predicted response:', y_pred, sep='\n')

In [ ]:
# Polynomial Regression

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [ ]:
# transform the input array x to contain the additional column(s) with the values of 𝑥² 

In [ ]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [ ]:
"""
several optional parameters to PolynomialFeatures:

degree is an integer (2 by default) that represents the degree of the 
                                       polynomial regression function.

interaction_only is a Boolean (False by default) that decides whether 
     to include only interaction features (True) or all features (False).

include_bias is a Boolean (True by default) that decides whether to include 
              the bias (intercept) column of ones (True) or not (False).
"""

In [ ]:
transformer.fit(x)

In [ ]:
x_ = transformer.transform(x)

In [ ]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [ ]:
print(x_)

In [ ]:
model = LinearRegression().fit(x_, y)

In [ ]:
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('coefficients:', model.coef_)

In [ ]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [ ]:
print(x_)

In [ ]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [ ]:
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

In [ ]:
_pred = model.predict(x_)

In [ ]:
print('predicted response:', y_pred, sep='\n')

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)


model = LinearRegression().fit(x_, y)

r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

y_pred = model.predict(x_)

In [ ]:
print('coefficient of determination:', r_sq)
print('intercept:', intercept)
print('coefficients:', coefficients, sep='\n')
print('predicted response:', y_pred, sep='\n')

In [ ]:
import numpy as np
import statsmodels.api as sm

In [ ]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], 
     [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [ ]:
x = sm.add_constant(x)

In [ ]:
print(x)

In [ ]:
print(y)

In [ ]:
model = sm.OLS(y, x)

In [ ]:
results = model.fit()

In [ ]:
print(results.summary())

In [ ]:
print('coefficient of determination:', results.rsquared)
print('adjusted coefficient of determination:', results.rsquared_adj)
print('regression coefficients:', results.params)

In [ ]:
#print('predicted response:', results.fittedvalues, sep='\n')
print('predicted response:', results.predict(x), sep='\n')

In [ ]:
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
print(x_new)

In [ ]:
y_new = results.predict(x_new)
print(y_new)